import html,json
from pathlib import Path
ROOT=Path(__file__).parent
products=json.loads((ROOT/'config/products.json').read_text()); details=json.loads((ROOT/'config/product_details.json').read_text()) if (ROOT/'config/product_details.json').exists() else {}
latest_path=ROOT/'data/latest.json'; latest=json.loads(latest_path.read_text()) if latest_path.exists() else {'generated_at':None,'observations':[]}
obs_by_product={}
for o in latest.get('observations',[]):obs_by_product.setdefault(o['product_id'],[]).append(o)
rows=[]
for p in products:
    obs=obs_by_product.get(p['id'],[]); verified=[o for o in obs if o.get('status')=='VERIFIED']; verified.sort(key=lambda o:(0,o['delivered_price']) if o.get('delivered_price') is not None else (1,o.get('price') or 10**9)); low=verified[0] if verified else None; d=details.get(p['id'],{})
    if low:
        item=f'${low["price"]:,.2f}'; shipping='FREE' if low.get('shipping')==0 else (f'${low["shipping"]:,.2f}' if low.get('shipping') is not None else 'TBD'); delivered=f'${low["delivered_price"]:,.2f}' if low.get('delivered_price') is not None else 'TBD'; cpp=f'${low["cost_per_pack"]:,.2f}' if low.get('cost_per_pack') is not None else '—'; seller=html.escape(low['seller']); buy=f'<a class="buy" href="{html.escape(low.get("final_url") or low["url"])}" target="_blank" rel="noopener">BUY</a>'
    else:item=shipping=delivered=cpp='—';seller='No verified stock';buy=''
    config=''; packs=d.get('packs_per_box'); cards=d.get('cards_per_pack')
    if packs and cards:config=f'{packs} packs × {cards} cards' + (f' + {d["bonus_cards"]} bonus cards' if d.get('bonus_cards') else '')
    guarantees=' · '.join('✓ '+html.escape(x) for x in d.get('guarantees',[])); possible=' · '.join('◇ '+html.escape(x) for x in d.get('possible_hits',[])); info='<br>'.join(x for x in [config,guarantees,possible] if x) or 'Product details pending validation'
    checklist=f'<a class="link" href="{html.escape(d["checklist_url"])}" target="_blank" rel="noopener">CHECKLIST</a>' if d.get('checklist_url') else '<span class="muted">Checklist pending</span>'
    status=[]
    for o in sorted(obs,key=lambda x:(x.get('status')!='VERIFIED',x.get('price') or 10**9)):
        icon={'VERIFIED':'🟢','OUT_OF_STOCK':'🔴','REJECTED':'🚫','UNKNOWN':'⚪'}.get(o.get('status'),'⚪'); amount=f'${o["price"]:,.2f}' if o.get('price') is not None else '—'; ship=' + FREE ship' if o.get('shipping')==0 else (' + ship TBD' if o.get('status')=='VERIFIED' and o.get('shipping') is None else '')
        status.append(f'{icon} {html.escape(o["seller"])} {amount}{ship}')
    details_text=' · '.join(status) if status else 'No retailer mappings yet'
    rows.append(f'''<tr data-season="{p['season']}" data-search="{html.escape((p['product']+' '+p['format']).lower())}"><td><strong>{p['season']}</strong></td><td><strong>{html.escape(p['product'])}</strong><div class="format">{html.escape(p['format'])}</div><div class="boxinfo">{info}</div>{checklist}</td><td class="price">{item}<div class="seller">{seller}</div></td><td>{shipping}</td><td class="delivered">{delivered}</td><td>{cpp}</td><td>{buy}</td><td class="details">{details_text}</td></tr>''')
generated=latest.get('generated_at') or 'Not collected yet'
page=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CardsInStock</title><style>:root{{--bg:#0b1020;--card:#121a2d;--line:#26324c;--text:#eef3ff;--muted:#9eabc5;--accent:#6ee7b7}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,sans-serif}}main{{max-width:1500px;margin:auto;padding:22px}}h1{{margin:0;font-size:28px}}.sub,.muted{{color:var(--muted)}}.sub{{margin:5px 0 18px}}.controls{{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px}}input,select{{background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px 12px;font-size:15px}}.table{{overflow:auto;border:1px solid var(--line);border-radius:12px}}table{{width:100%;border-collapse:collapse;min-width:1150px;background:var(--card)}}th,td{{padding:13px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{position:sticky;top:0;background:#172139;font-size:12px;text-transform:uppercase;color:var(--muted)}}.format,.seller,.details,.boxinfo{{color:var(--muted);font-size:12px;margin-top:3px}}.boxinfo{{max-width:390px;line-height:1.45}}.price,.delivered{{font-weight:800;white-space:nowrap}}.delivered{{color:var(--accent)}}.buy,.link{{display:inline-block;text-decoration:none;font-weight:900;border-radius:8px}}.buy{{background:var(--accent);color:#07130e;padding:8px 12px}}.link{{color:var(--accent);font-size:11px;margin-top:7px}}.details{{max-width:430px}}@media(max-width:650px){{main{{padding:14px}}h1{{font-size:24px}}}}</style></head><body><main><h1>CardsInStock</h1><div class="sub">Accuracy-first soccer wax tracker · {len(products)} products · Last collection: {html.escape(str(generated))}</div><div class="controls"><input id="q" placeholder="Search product…"><select id="season"><option value="">All seasons</option><option>2023-24</option><option>2024-25</option><option>2025-26</option><option>2026-27</option></select></div><div class="table"><table><thead><tr><th>Season</th><th>Product / Box contents</th><th>Item price</th><th>Shipping</th><th>Delivered</th><th>$/Pack</th><th></th><th>Retailer checks</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><script>const q=document.querySelector('#q'),s=document.querySelector('#season'),rows=[...document.querySelectorAll('tbody tr')];function f(){{let x=q.value.toLowerCase(),y=s.value;rows.forEach(r=>r.style.display=(!x||r.dataset.search.includes(x))&&(!y||r.dataset.season===y)?'':'none')}}q.oninput=f;s.onchange=f;</script></main></body></html>'''
(ROOT/'docs').mkdir(exist_ok=True);(ROOT/'docs/index.html').write_text(page);(ROOT/'docs/latest.json').write_text(json.dumps(latest,indent=2));print(f'Built dashboard with {len(products)} products')
